[[choice]]
  name = "List organisations"
  query = "SELECT * FROM organisation"

[[choice]]
  name = "List organisation subscriptions"
  query = "SELECT * FROM organisation_subscription"

[[choice]]
  name = "Select all users from businesstest"
  query = "SELECT * FROM businesstest.user_profile"

[[choice]]
  name = "List all framework api keys"
  query = "SELECT * from businesstest.api_key"
